// demos/demo-react/src/components/QuizEditor.tsx
import React, { useRef, useEffect, useImperativeHandle, forwardRef } from 'react';
import { QuizEditor } from '@quizerjs/quizerjs';
import type { QuizEditorOptions } from '@quizerjs/quizerjs';
import type { QuizDSL } from '@quizerjs/dsl';
import type { EditorJS } from '@editorjs/editorjs';

export interface QuizEditorProps {
  /** 初始 DSL 数据（可选） */
  initialDSL?: QuizDSL;
  /** 只读模式（可选，默认 false） */
  readOnly?: boolean;
  /** 数据变化事件 */
  onChange?: (dsl: QuizDSL) => void;
  /** 保存事件 */
  onSave?: (dsl: QuizDSL) => void;
}

export interface QuizEditorRef {
  getEditorInstance: () => EditorJS | null;
  save: () => Promise<QuizDSL | null>;
  load: (dsl: QuizDSL) => Promise<void>;
  clear: () => Promise<void>;
  isDirty: () => boolean;
}

const QuizEditorComponent = forwardRef<QuizEditorRef, QuizEditorProps>(
  ({ initialDSL, readOnly = false, onChange, onSave }, ref) => {
    const editorContainerRef = useRef<HTMLDivElement>(null);
    const editorRef = useRef<QuizEditor | null>(null);
    // 使用 ref 存储回调，避免 useEffect 重复执行
    const onChangeRef = useRef(onChange);
    const onSaveRef = useRef(onSave);

    // 更新回调 ref
    useEffect(() => {
      onChangeRef.current = onChange;
      onSaveRef.current = onSave;
    }, [onChange, onSave]);

    useEffect(() => {
      if (!editorContainerRef.current) return;

      // 如果已经初始化过，先销毁
      if (editorRef.current) {
        editorRef.current.destroy();
        editorRef.current = null;
      }

      const initEditor = async () => {
        try {
          const options: QuizEditorOptions = {
            container: editorContainerRef.current!,
            initialDSL,
            readOnly,
            onChange: (dsl) => {
              if (onChangeRef.current) {
                onChangeRef.current(dsl);
              }
            },
            onSave: (dsl) => {
              if (onSaveRef.current) {
                onSaveRef.current(dsl);
              }
            },
          };

          const editor = new QuizEditor(options);
          await editor.init();
          editorRef.current = editor;
        } catch (error) {
          console.error('初始化 QuizEditor 失败:', error);
        }
      };

      initEditor();

      return () => {
        if (editorRef.current) {
          editorRef.current.destroy();
          editorRef.current = null;
        }
      };
    }, [initialDSL, readOnly]);

    useImperativeHandle(ref, () => ({
      getEditorInstance: () => {
        return editorRef.current?.getEditorInstance() || null;
      },
      save: async () => {
        if (!editorRef.current) return null;
        const dsl = await editorRef.current.save();
        if (onSave) {
          onSave(dsl);
        }
        return dsl;
      },
      load: async (dsl: QuizDSL) => {
        if (editorRef.current) {
          await editorRef.current.load(dsl);
        }
      },
      clear: async () => {
        if (editorRef.current) {
          await editorRef.current.clear();
        }
      },
      isDirty: () => {
        return editorRef.current?.isDirty || false;
      },
    }));

    return <div ref={editorContainerRef} className="quiz-editor" />;
  }
);

QuizEditorComponent.displayName = 'QuizEditor';

export default QuizEditorComponent;

// demos/demo-svelte/src/components/QuizEditor.svelte
<svelte:options accessors={true} />

<script lang="ts">
  import { onMount, onDestroy, tick } from 'svelte';
  import { QuizEditor } from '@quizerjs/quizerjs';
  import type { QuizEditorOptions } from '@quizerjs/quizerjs';
  import type { QuizDSL } from '@quizerjs/dsl';
  import type { EditorJS } from '@editorjs/editorjs';

  export interface QuizEditorRef {
    getEditorInstance: () => EditorJS | null;
    save: () => Promise<QuizDSL | null>;
    load: (dsl: QuizDSL) => Promise<void>;
    clear: () => Promise<void>;
    isDirty: () => boolean;
  }

  export let initialDSL: QuizDSL | undefined = undefined;
  export let readOnly: boolean = false;
  export let onChange: ((dsl: QuizDSL) => void) | undefined = undefined;
  export let onSave: ((dsl: QuizDSL) => void) | undefined = undefined;

  let editorContainer: HTMLDivElement;
  let editorInstance: QuizEditor | null = null;

  // 导出 ref 给父组件使用
  // 在 Svelte 中，通过 bind:this 获取的组件实例只能访问使用 export let 导出的变量
  // 即使它是 prop，如果父组件不传递值，它会保持初始值，然后在 onMount 中被赋值
  export let editorRef: QuizEditorRef | null = null;

  onMount(async () => {
    if (!editorContainer) return;

    const initEditor = async () => {
      try {
        const options: QuizEditorOptions = {
          container: editorContainer,
          initialDSL,
          readOnly,
          onChange: dsl => {
            if (onChange) {
              onChange(dsl);
            }
          },
          onSave: dsl => {
            if (onSave) {
              onSave(dsl);
            }
          },
        };

        const editor = new QuizEditor(options);
        await editor.init();
        editorInstance = editor;

        // 创建 ref 对象
        editorRef = {
          getEditorInstance: () => {
            return editorInstance?.getEditorInstance() || null;
          },
          save: async () => {
            if (!editorInstance) return null;
            const dsl = await editorInstance.save();
            if (onSave) {
              onSave(dsl);
            }
            return dsl;
          },
          load: async (dsl: QuizDSL) => {
            if (editorInstance) {
              await editorInstance.load(dsl);
            }
          },
          clear: async () => {
            if (editorInstance) {
              await editorInstance.clear();
            }
          },
          isDirty: () => {
            return editorInstance?.isDirty || false;
          },
        };

        // 等待 Svelte 更新，确保 ref 被正确绑定
        await tick();
      } catch (error) {
        console.error('初始化 QuizEditor 失败:', error);
      }
    };

    await initEditor();
  });

  onDestroy(() => {
    if (editorInstance) {
      editorInstance.destroy();
      editorInstance = null;
    }
  });

  // 导出 ref 给父组件使用（通过 export 使其可被外部访问）
  // 注意：在 Svelte 中，通过 bind:this 获取组件实例后，可以访问所有导出的变量
</script>

<div bind:this={editorContainer} class="quiz-editor" />
